oursite/SAM2017/urls.py
from django.conf.urls import url
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'SAM2017'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^papers/$', views.view_papers, name='view-papers'),
    url(r'^upload-paper/$', views.upload_paper, name='upload-paper'),
   # url(r'^review-rate/$', views.reviewRating, name='review-rate'),
    #url(r'^papers/paper-upload/uploaded_files/(?P<papername>)/$',views.download_paper, name='download-paper')


] +static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

oursite/oursite/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views
from django.core.urlresolvers import reverse


from SAM2017 import views as sam_views
from SAM2017.forms import *
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    # index page, i.e. Homepage after log-in
    url(r'^$', sam_views.index, name='index'),

    # Log-in page
    url(r'^login/$', sam_views.login, {'template_name': 'user/login.html', 'authentication_form': LoginForm}, name="login"),
    url(r'^logout/$', views.logout, {'next_page': '/login'}),

    url(r'^admin/', admin.site.urls),
    url(r'^SAM2017/', include('SAM2017.urls', namespace='SAM2017')),

    # registration page
    url(r'^register/$', sam_views.register, name='register'),
    url(r'^register/success$', sam_views.register_complete, name='register_complete'),

    url(r'^papers/$', sam_views.view_papers, name='view-papers'),
    url(r'^upload-paper/$', sam_views.upload_paper, name='upload-paper'),
    url(r'^upload-another-version/(?P<paperId>[0-9]+)/$', sam_views.upload_another_version, name='upload-paper-version'),
    url(r'^papers/paper-details/(?P<paperId>[0-9]+)/$', sam_views.paper_details, name='paper-details'),
    url(r'^doc-uploads/uploaded_files/(?P<papername>.*\.pdf)/$', sam_views.download_paper, name='download-paper'),
    url(r'^review-rate/(?P<paperId>\d+)', sam_views.reviewRating, name='review-rate'),
    url(r'^paper_details_author/(?P<paperId>[0-9]+)/$', sam_views.paper_details_author, name='paper_details_author'),
    url(r'^paper-details/(?P<paperId>[0-9]+)/$', sam_views.paper_details, name='paper-details'),

    url(r'^review-rate/(?P<paperId>\d+)', sam_views.reviewRating, name='review-rate'),

    #PCM functions
    url(r'^paper_selection_pcm/$',sam_views.paper_selection_pcm,name='paper_selection_pcm'),
    url(r'^request_to_review/(?P<paperId>\d+)/',sam_views.request_to_review,name='request_to_review'),
    url(r'^selected_to_review_pcm/$',sam_views.selected_to_review_pcm,name='selected_to_review_pcm'),
    url(r'^view_notifications_pcm/$', sam_views.view_notifications_pcm, name='view_notifications_pcm'),


    #PCC functions
    url(r'^paper-details_pcc/(?P<paperId>[0-9]+)/$', sam_views.paper_details_pcc, name='paper-details_pcc'),
    url(r'^paper-approve/(?P<Id>[0-9]+)/$', sam_views.paper_approve, name='paper-approve'),
    url(r'^paper-reject/(?P<Id>[0-9]+)/$', sam_views.paper_reject, name='paper-reject'),
    url(r'^paper_assignment_pcc/$', sam_views.paper_assignment_pcc, name='paper_assignment_pcc'),
    url(r'^view_requests_pcc/$', sam_views.view_requests_pcc, name='view_requests_pcc'),
    url(r'^paper_selected_to_assign/(?P<paperId>[0-9]+)/$', sam_views.paper_selected_to_assign, name='paper_selected_to_assign'),
    url(r'^assigned_reviewer/(?P<paperId>[0-9]+)/(?P<reviewerId>[0-9]+)/$', sam_views.assigned_reviewer,name='assigned_reviewer'),
    url(r'^promote_to_pcm/$', sam_views.promote_to_pcm, name='promote_to_pcm'),
    url(r'^promote_author/(?P<uid>[0-9]+)/$', sam_views.promote_author, name='promote_author'),
    url(r'^view_papers_to_review/$', sam_views.view_papers_to_review, name='view_papers_to_review'),
    url(r'^paper_review_pcc/(?P<paperId>[0-9]+)/$', sam_views.paper_review_pcc, name='paper_review_pcc'),
    url(r'^review_rate_pcc/(?P<paperId>[0-9]+)/$', sam_views.review_rate_pcc, name='review_rate_pcc'),
    url(r'^notifications_pcc/$', sam_views.view_notifications_pcc, name='view-notifications_pcc'),


    url(r'^notifications/$', sam_views.view_notifications, name='view-notifications'),
    url(r'^delete_notifications/$', sam_views.delete_notifications, name='delete_notifications'),
    url(r'^delete_notifications_pcc/$', sam_views.delete_notifications_pcc, name='delete_notifications_pcc'),
    url(r'^deadlines/$', sam_views.view_deadlines, name='view-deadlines'),
    url(r'^update-deadlines/$', sam_views.update_deadlines, name='update-deadlines'),
    url(r'^sam/admin/accounts/$', sam_views.accounts, name='manage-accounts'),
    url(r'^deleteuser/(?P<userId>[0-9]+)/$', sam_views.deleteUser, name='delete-user'),
    url(r'^promoteauthor/(?P<userId>[0-9]+)/$', sam_views.promoteAuthor, name='promote-author'),
    url(r'^demotepcm/(?P<userId>[0-9]+)/$', sam_views.demotePCM, name='promote-author'),
]

oursite/SAM2017/forms.py
from django import forms
from SAM2017.models import *
import datetime
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.utils.translation import gettext as _
from django.contrib.auth import password_validation
from django.forms.models import ModelForm
from django.contrib.admin import widgets
from datetime import datetime, date, time, timedelta

class PaperForm(forms.ModelForm):
    class Meta:
        model = Paper
        fields = ('title','description','file','authors')


class VersionForm(forms.ModelForm):
    class Meta:
        model = Paper
        fields = ('file','authors')

class LoginForm(AuthenticationForm):
    username = forms.CharField(label="Email", max_length=30)
    password = forms.CharField(label="Password", max_length=30, min_length=8, widget=forms.PasswordInput())
    
    class Meta:
        model = SAMUser


class UserCreationForm(UserCreationForm):
    username = forms.EmailField(label=_("Email"), widget=forms.EmailInput)
    first_name = forms.CharField(label=_("First Name"), widget=forms.TextInput)
    last_name = forms.CharField(label=_("Last Name"), widget=forms.TextInput)
    address = forms.CharField(label=_("Address"), widget=forms.Textarea)
    phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$', message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.")
    phone_number = forms.CharField(validators=[phone_regex], label=_("Phone Number"))
    
    class Meta:
        model = SAMUser
        fields = ("username",)
    
    def save(self, commit=True):
        user = super(UserCreationForm, self).save(commit=False)
        # copy the submitted cleaned form-data to the user's properties
        user.set_password(self.cleaned_data["password1"])
        user.username = self.cleaned_data["username"]
        user.first_name = self.cleaned_data["first_name"]
        user.last_name = self.cleaned_data["last_name"]
        user.address = self.cleaned_data["address"]
        user.phone_number = self.cleaned_data["phone_number"]
        user.is_admin = False
        if commit:
            # save the user properties to the db fields
            user.save()
        return user

class ReviewRateForm(forms.ModelForm):
    class Meta:
        model = ReviewRating
        fields = ('review','rating')

oursite/SAM2017/views.py
from django.conf import settings
from django.contrib.auth import authenticate, login as auth_login, get_user, \
    REDIRECT_FIELD_NAME
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import deprecate_current_app
from django.contrib.sites.shortcuts import get_current_site
from django.core.context_processors import csrf
from django.core.urlresolvers import reverse, reverse_lazy
from django.db import connection
from django.http.response import HttpResponseRedirect
from django.shortcuts import render, render_to_response, redirect, resolve_url, \
    get_object_or_404
from django.template.context import RequestContext
from django.db.models import Count
from django.template.context_processors import request
from django.template.response import TemplateResponse
from django.utils.http import is_safe_url
from django.views.generic.edit import UpdateView
from SAM2017.forms import *
from SAM2017.models import *
import json
from django.utils.encoding import smart_str

import functools
import warnings

# Avoid shadowing the login() and logout() views below.
from django.contrib.auth import (
    REDIRECT_FIELD_NAME, get_user_model, login as auth_login,
    logout as auth_logout, update_session_auth_hash,
)
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import (
    AuthenticationForm, PasswordChangeForm, PasswordResetForm, SetPasswordForm,
)
from django.contrib.auth.tokens import default_token_generator
from django.contrib.sites.shortcuts import get_current_site
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect, QueryDict
from django.shortcuts import resolve_url
from django.template.response import TemplateResponse
from django.utils.deprecation import (
    RemovedInDjango20Warning, RemovedInDjango110Warning,
)
from django.utils.encoding import force_text
from django.utils.http import is_safe_url, urlsafe_base64_decode
# from django.utils.six.moves.urllib.parse import urlparse, urlunparse
from django.utils.translation import ugettext as _
from django.views.decorators.cache import never_cache
from django.views.decorators.csrf import csrf_protect
from django.views.decorators.debug import sensitive_post_parameters



from django.http import HttpResponse

SAM_login_url = reverse_lazy("login")
home_page = reverse_lazy("home")

#index page, i.e. Homepage after log-in
@login_required(login_url=SAM_login_url)
def index(request):
    if request.user.is_admin:
        return HttpResponseRedirect('/sam/admin/accounts/')

    u_id=request.user.id
    token={}
    if(PCC.objects.filter(id = u_id)):
        token['papers'] = Paper.objects.all()
        token['papers_assigned'] = papers_selection.objects.filter(decisions=True)
        token['papers_reviewed'] = ReviewRating.objects.all()
        return render_to_response('common/pcc_home.html',token)
    elif(PCM.objects.filter(id = u_id)):
        token['papers'] = Paper.objects.all()
        return render_to_response('common/pcm_home.html',token)
    return render_to_response('common/index.html')


@login_required(login_url=SAM_login_url)
def pcc_home(request):
    id=request.user.id
    return render_to_response('common/pcc_home.html')

@login_required(login_url=SAM_login_url)
def view_papers_to_review(request):
    token={}
    reviews_done = ReviewRating.objects.values('paper_id').annotate(dcount=Count('paper_id')).filter(dcount=3)
    pcc_to_review = []
    i = 0
    for rev in reviews_done:
        pap = Paper.objects.get(id=reviews_done[i]['paper_id'])
        pcc_to_review.append(pap)
        i = i + 1
    token['pcc_to_review'] = pcc_to_review
    token['papers'] = Paper.objects.all()
    return render_to_response('common/view_papers_to_review.html',token)

@login_required(login_url=SAM_login_url)
def paper_review_pcc(request,paperId):
    paper=Paper.objects.get(id=paperId)
    token={}
    token['paper']=paper
    return render_to_response('common/paper_review_pcc.html',token)

@login_required(login_url=SAM_login_url)
def review_rate_pcc(request,paperId):
    paper=Paper.objects.get(id=paperId)
    user = request.user
    if request.method == 'POST':

        # create a form instance and populate it with data from the request
        form = ReviewRateForm(data=request.POST)

        if form.is_valid():
            new = ReviewRating(reviwer_id=user.id, paper_id=paper.id, review=form.cleaned_data["review"],
                               rating=form.cleaned_data["rating"],is_Final=True)
            new.save()
            return HttpResponseRedirect(resolve_url('view_papers_to_review'))

    else:
        form = ReviewRateForm()

    token = {}
    token['paper'] = paper
    token.update(csrf(request))
    token['form'] = form
    return render_to_response('common/review_rate_pcc.html', token)


@login_required(login_url=SAM_login_url)
def upload_paper(request):
    if request.POST:
        form = PaperForm(request.POST,request.FILES)
        if form.is_valid():
            form.save()
            notification = Notification()
            users = PCC.objects.first()
            recipient = [users]
            notification.save()
            notification.sendNotification('NEW_PAPER', recipient)
            return HttpResponseRedirect('/papers/')
    else:
        form = PaperForm()
    args={}
    args.update(csrf(request))
    args['form']=form
    print(request.user.id)
    args['userid']=request.user.id
    return render_to_response('common/upload-paper.html',args)


@login_required(login_url=SAM_login_url)
def upload_another_version(request, paperId):
    paper = Paper.objects.get(id=paperId)
    if request.POST:
        form = VersionForm(request.POST,request.FILES)
        if form.is_valid():
            paper.file = form.cleaned_data['file']
            paper.version += 1
            paper.save()
            notification = Notification()
            users = PCC.objects.first()
            recipient = [users]
            notification.save()
            notification.sendNotification('NEW_PAPER', recipient)
            return HttpResponseRedirect('/papers/')
    else:
        form = VersionForm()
    args={}
    args.update(csrf(request))
    args['form']=form
    print(request.user.id)
    args['userid']=request.user.id
    return render_to_response('common/upload_version.html',args)


@login_required(login_url=SAM_login_url)
def paper_details_author(request,paperId):
    paper = Paper.objects.get(id=paperId)
    token={}
    reviews=ReviewRating.objects.filter(paper_id=paperId)
    author=SAMUser.objects.get(id=paper.authors_id)
    pcm=PCM.objects.all()
    pcc=PCC.objects.first()
    token['pcc']=pcc
    token['pcm']=pcm
    token['paper']=paper
    token['user_id']=request.user.id
    token['author'] = author
    token['reviews']=reviews
    return render_to_response('common/paper_details_author.html',token)

@login_required(login_url=SAM_login_url)
def view_papers(request):
    author_id=request.user.id
    paper_ids = Paper.objects.filter(authors=author_id)
    context = {'papers': paper_ids}
    return render(request, 'common/view-papers.html', context, context_instance=RequestContext(request))

@login_required(login_url=SAM_login_url)
def paper_assignment_pcc(request):
    token={}
    papers = Paper.objects.filter(numofreviewers__lte=2)
    token['papers'] = papers
    return render_to_response("common/paper_assignment_pcc.html",token)

@login_required(login_url=SAM_login_url)
def paper_selected_to_assign(request,paperId):
    token={}
    reviewers=[]
    paper = Paper.objects.get(id=paperId)
    if paper.numofreviewers >= 3:
        return HttpResponseRedirect(resolve_url('paper_assignment_pcc'))
    list_of_reviewers = PCM.objects.all().exclude(id=paper.authors_id)
    for li in list_of_reviewers:
        abc = papers_selection.objects.filter(selected_paper_id=paperId).filter(pcm_id=li.id).filter(decisions=True)
        if abc:
            print('')
        else:
            reviewers.append(li)
    token['paper'] = paper
    token['reviewers'] = reviewers
    return render_to_response("common/paper_selected_to_assign.html",token)

@login_required(login_url=SAM_login_url)
def assigned_reviewer(request, paperId,reviewerId):
    token={}
    paper=Paper.objects.get(id=paperId)
    if paper.numofreviewers < 3:
        new_add = papers_selection.objects.create(decisions=True,selected_paper_id=paperId,pcm_id=reviewerId)
        paper.numofreviewers = paper.numofreviewers + 1
        paper.save()
        new_add.save()
        notification = Notification()
        users = PCM.objects.get(id=reviewerId)
        recipient = [users]
        notification.save()
        notification.sendNotification('PAPER_ASSIGNED', recipient)
        if paper.numofreviewers == 3:
            return HttpResponseRedirect(resolve_url('paper_assignment_pcc'))
        return HttpResponseRedirect(resolve_url('/paper_selected_to_assign/'+paperId+'/', token))
    else:
        return HttpResponseRedirect(resolve_url('paper_assignment_pcc'))
@login_required(login_url=SAM_login_url)
def paper_selection_pcm(request):
    token={}
    new_paper_list=[]
    token['user_id'] = request.user.id
    token['samuser']=SAMUser.objects.all();
    paper_list = Paper.objects.filter(numofreviewers__lte= 2).exclude(authors_id=request.user.id)
    for paper in paper_list:
        pap=papers_selection.objects.filter(selected_paper_id=paper.id).filter(pcm_id=request.user.id)
        if pap:
            print('')
        else:
            new_paper_list.append(paper)
    token['paper_list']=new_paper_list
    return render_to_response('common/paper_selection.html',token)

@login_required(login_url=SAM_login_url)
def request_to_review(request,paperId):
    pcm_user = request.user.id
    pap = paperId
    papers_selection.create(pcm_user,pap)
    notification = Notification()
    users = PCC.objects.first()
    recipient = [users]

oursite/SAM2017/templates/common/admin_manage_accounts.html
{% extends 'common/base_admin.html' %}
{% block title %}SAM2017- Manage accounts{% endblock %}
{% block navbar_index %}active{% endblock %}

{% block body %}
<table class="accounts-table">
<tr class="header-row"><td colspan="3"><div class="authors">Authors</div></td></tr>
    {% for account in authors %}
    <tr>
        <td><div class="account-block">{{account.first_name}} {{account.last_name}}</div></td>
        <td><button class="btn btn-danger delete-user-btn" data-user-id={{account.id}}><span class="glyphicon glyphicon-trash"></span></button></td>
        <td><button class="btn btn-primary promote-author" data-user-id={{account.id}}>Promote to PCM</button></td>
    </tr>
    {% endfor %}

<tr class="header-row"><td colspan="3"><div class="authors">PCC</div></td></tr>

    {% for account in pcc %}
    <tr>
        <td><div class="account-block">{{account.first_name}} {{account.last_name}}</div></td>
        <td><button class="btn btn-danger delete-user-btn" data-user-id={{account.id}}><span class="glyphicon glyphicon-trash"></span></button></td>
        <td></td>
    </tr>
    {% endfor %}

<tr class="header-row"><td colspan="3"><div class="authors">PCM</div></td></tr>

    {% for account in pcm %}
    <tr>
        <td><div class="account-block">{{account.first_name}} {{account.last_name}}</div></td>
        <!--<button class="btn btn-warning demote-pcm" data-user-id={{account.id}}>Demote to Author</button>-->
        <td><button class="btn btn-danger delete-user-btn" data-user-id={{account.id}}><span class="glyphicon glyphicon-trash"></span></button></td>
        <td></td>
    </tr>
    {% endfor %}


<tr class="header-row"><td colspan="3"><div class="authors">Admins</div></td></tr>

    {% for account in admins %}
    <tr>
        <td><div class="account-block">{{account.first_name}} {{account.last_name}}</div></td>
        <td><button class="btn btn-danger delete-user-btn" data-user-id={{account.id}}><span class="glyphicon glyphicon-trash"></span></button></td>
        <td></td>
    </tr>
    {% endfor %}
</table>
<script type="text/javascript">
    $(document).ready(function(){
        $('.delete-user-btn').on('click', deleteUser);
        $('.promote-author').on('click', promoteAuthor);
        $('.demote-pcm').on('click', demotePCM);
    });

    function deleteUser(event){
        var id = $(event.target).data('user-id');
        $.ajax({
            url: '/deleteuser/'+id+'/',
            dataType: 'json',
            success: function(data){
                var jsonData = JSON.parse(data);
                if(jsonData['success'] == 1){
                    window.location.reload(true);
                }
            },
            error: function (data) {
            	console.log("delete user error");
                console.log(data);
            }
        });
    }

    function promoteAuthor(event){
        var id = $(event.target).data('user-id');
        $.ajax({
            url: '/promoteauthor/'+id+'/',
            dataType: 'json',
            success: function(data){

                if(data['success'] == 1){
                    window.location.reload(true);
                }
            },
            error: function (data) {
            	console.log("delete user error");
                console.log(data);
            }
        });
    }

    function demotePCM(event){
        var id = $(event.target).data('user-id');
        $.ajax({
            url: '/demotepcm/'+id+'/',
            dataType: 'json',
            success: function(data){

                if(data['success'] == 1){
                    window.location.reload(true);
                }
            },
            error: function (data) {
            	console.log("delete user error");
                console.log(data);
            }
        });
    }
</script>
{% endblock %}

oursite/SAM2017/templates/common/base_pcm.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}SAM2017{% endblock %}</title>

    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'SAM2017/css/bootstrap.min.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'SAM2017/css/style.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'SAM2017/css/jquery-ui.min.css' %}"/>
    <link href="https://fonts.googleapis.com/css?family=Oswald" rel="stylesheet">
    <script src="{% static 'SAM2017/js/jquery-3.1.1.min.js' %}"></script>
    <script src="{% static 'SAM2017/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'SAM2017/js/jquery-ui.min.js' %}"></script>
</head>


<body>
<nav class="navbar navbar-default">
    <div class="container-fluid">

        <!--Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar">Upload Paper</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'SAM2017:index' %}">SAM2017</a>
        </div>
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
               {% comment %} {% if user.is_authenticated  %}{% endcomment %}
                    <li class="{% block navbar_view-papers %}{% endblock %}">
                        <a href="{% url 'SAM2017:view-papers' %}">
                            <span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>&nbsp;
                            My Papers
                        </a>
                    </li>

                    <li class="{% block navbar_upload-paper %}{% endblock %}">
                        <a href="{% url 'SAM2017:upload-paper' %}">
                            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp;
                            Submit Paper
                        </a>
                    </li>

                {% comment %}{% else %}
                    <li class="{% block navbar_signin %}{% endblock %}">
                        <a href="{% url 'SAM2017.views.login' %}">
                            <span class="glyphicon glyphicon-log-in" aria-hidden="true"></span>&nbsp;
                            Signin
                        </a>
                    </li>
                    <li class="{% block navbar_register-user %}{% endblock %}">
                        <a href="{% url 'SAM2017.views.register' %}">
                            <span class="glyphicon glyphicon-registration-mark" aria-hidden="true"></span>&nbsp;
                            Register
                        </a>
                    </li>
            {% endif %}{% endcomment %}
            </ul>

            <ul class="nav navbar-nav navbar-right">
                {% comment %}{% if user.is_authenticated %}{% endcomment %}


                    <li class="{% block navbar_view-notifications %}{% endblock %}">
                        <a href="{% url 'view_notifications_pcm' %}">
                            <span class="glyphicon glyphicon-bell" aria-hidden="true"></span>&nbsp;
                            Notifications
                        </a>
                    </li>
                <li class="">
                        <a href="/logout/">
                            <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp;
                            Logout
                        </a>
                    </li>


            </ul>

        </div>

    </div>
</nav>

    {% block body %}
    {% endblock %}



<hr>


</body>
</html>

oursite/SAM2017/templates/common/home.html
<h2>Welcome to SAM2017 </h2>
<p>SAM2017 for the amazing advancements in Software Engineering....</p>

oursite/SAM2017/templates/common/notifications_pcc.html
{% extends 'common/base_pcc.html' %}
{% block title %}SAM2017 - View Notifications{% endblock %}
{% block navbar_view-notifications %}active{% endblock %}

{% block body %}       {% block side_nav %}
<nav class="sidenavpcc" style="width:12%;position: absolute">
    <a href="/paper_assignment_pcc/" class="list-group-item" id="link_mbr">Assign Papers</a>
    <a href="/view_requests_pcc/" class="list-group-item" id="link_stat">Review Requests</a>
    <a href="/promote_to_pcm/" class="list-group-item" id="link_promote">Promote Authors</a>
<a href="/view_papers_to_review/" class="list-group-item" id="link_reiew">Review Rate</a>
</nav>
{% endblock %}
    {% block maincontent %}
         <div class="container" style="margin-left: 15%;">
    {% comment %}{% if user.is_authenticated %}{% endcomment %}
    {% if notifications %}
        <ul class="list-group">
        {% for notification in notifications %}
            <li class="list-group-item">
            <strong>{{ notification.title }}</strong>
            <h5>{{ notification.message }}</h5>
            </li>
        {% endfor %}
        <button type="button" onclick="window.location.href='/delete_notifications_pcc/'">Delete Notifications</button>     </ul>
    {% else %}
        <p> You have no notifications</p>
    {% endif %}
   {% comment %} {% else %}
        <p>Please login to view your notifications</p>
    {% endif %}{% endcomment %}</div>{% endblock %}
{% endblock %}

oursite/SAM2017/templates/common/notifications_pcm.html
{% extends 'common/base_pcc.html' %}
{% block title %}SAM2017 - View Notifications{% endblock %}
{% block navbar_view-notifications %}active{% endblock %}

{% block body %}
  {% block side_nav %}
<nav class="sidenavpcc" style="width:12%;position: absolute">
   <a href="/selected_to_review_pcm/" class="list-group-item active" id="link_mbr">Review Papers</a>
    <a href="/paper_selection_pcm/" class="list-group-item" id="link_stat">Select Paper to Review</a>
</nav>
{% endblock %}
    {% block maincontent %}
        <div class="container" style="margin-left: 15%;">
    {% comment %}{% if user.is_authenticated %}{% endcomment %}
    {% if notifications %}
        <ul class="list-group">
        {% for notification in notifications %}
            <li class="list-group-item">
            <strong>{{ notification.title }}</strong>
            <h5>{{ notification.message }}</h5>
            </li>
        {% endfor %}
        <button type="button" onclick="window.location.href='/delete_notifications_pcc/'">Delete Notifications</button>     </ul>
    {% else %}
        <p> You have no notifications</p>
    {% endif %}
   {% comment %} {% else %}
        <p>Please login to view your notifications</p>
    {% endif %}{% endcomment %}</div>{% endblock %}
{% endblock %}

oursite/SAM2017/templates/common/paper_selection_success.html
{% extends 'common/base_pcm.html' %}
{% block title %}SAM2017- Welcome{% endblock %}
{% block navbar_index %}active{% endblock %}

{% block body %}
  {% block side_nav %}
<nav class="sidenavpcc" style="width:12%;position: absolute">
   <a href="/selected_to_review_pcm/" class="list-group-item" id="link_mbr">Review Papers</a>
    <a href="/paper_selection_pcm/" class="list-group-item active" id="link_stat">Select Paper to Review</a>
</nav>
{% endblock %}
    {% block maincontent %}
        <div class="container" style="margin-left: 15%;">


        <p>Request has been sent to PCC for approval. Thank you.</p>
    </div>{% endblock %}
{% endblock %}